### ISSUE TITLE
line 513

### ISSUE THREAD

**Issue by ilkerat** [BlockchainTokenSniper/BSCTokenSniper#66]
[ERROR] foundToken error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 513, in foundToken
TypeError: string indices must be integers

**Comment by nickyoung92** [comment]
Same issue here. Even after rugdoc pass. Any fix?

**Comment by BlockchainTokenSniper** [comment]
Use latest version in telegram testing group
