### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by axel2200** [BlockchainTokenSniper/BSCTokenSniper#68]
hi! I'm getting for 1.3 the following error:

BSCTokenSniper v1.3

Traceback (most recent call last):
  File "BSCTokenSniper.py", line 63, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/BSCTokenSniper/BSCToken\\config.json'

Running on Amazon Linux OS
Any idea how to workaround ? looks is not able to find the config.json event thought is in the same folder..

Thanks

**Comment by BlockchainTokenSniper** [comment]
Use v1.4
