### ISSUE TITLE
Release source code

### ISSUE THREAD

**Issue by YuriPopiv** [BlockchainTokenSniper/BSCTokenSniper#71]
Is it possible to release source code?

**Comment by Tulle121** [comment]
Strange as it was for us all to run unknown binaries with our keys, this project is not intended to be open source. The Project owner has made it very clear to the community that this is not in the plans.

**Comment by BlockchainTokenSniper** [comment]
The project will never be open source. Reasons why are explained in the readme file. If you're hesitant about any issues use a fresh wallet with a small amount of BNB and transfer any profits to your main wallet.
