### ISSUE TITLE
WSS network spam

### ISSUE THREAD

**Issue by Tulle121** [BlockchainTokenSniper/BSCTokenSniper#73]
Aside from running your own node you must used a paid service, which are metered in some way unless you wanna pay $500+/mo. Look how hard the multi took slams eth_getFilterChanges:

![image](https://user-images.githubusercontent.com/449031/140904052-1f74fd0c-99c6-4160-a633-9917e447fcd2.png)

Is there any way to limit this? do we need to be THAT fast?

**Comment by BlockchainTokenSniper** [comment]
Are you using the launch or multi sniper?

I will try to implement a call throttling function in the future to reduce the calls made
