### ISSUE TITLE
[ERROR] foundToken error, please notify dev: Traceback (most recent call last):   File "BSCMultiSniper.py", line 234,

### ISSUE THREAD

**Issue by masmacer** [BlockchainTokenSniper/BSCTokenSniper#74]
![image](https://user-images.githubusercontent.com/20383513/141111466-fd0ca8e4-66d6-48cb-bf11-eea33b109b2b.png)

**Comment by BlockchainTokenSniper** [comment]
The multi sniper is getting a major upgrade and staysafu will likely not be used anymore.
