### ISSUE TITLE
Not selling?

### ISSUE THREAD

**Issue by nickyoung92** [BlockchainTokenSniper/BSCTokenSniper#78]
Set the bot to sell at 2x, and I have tokens going 4x and not selling. Not that I'm complaining since I sold manually, but if I wasn't here monitoring I could miss it. Any reason? fix? Appreciated.

**Comment by BlockchainTokenSniper** [comment]
What version of the bot are you using?

**Comment by ChimezieMadukwe** [comment]
> Set the bot to sell at 2x, and I have tokens going 4x and not selling. Not that I'm complaining since I sold manually, but if I wasn't here monitoring I could miss it. Any reason? fix? Appreciated.

What version are you using?

**Comment by BlockchainTokenSniper** [comment]
You should use v1.4 in telegram group.
