### ISSUE TITLE
Launcher Just Closes

### ISSUE THREAD

**Issue by MildAnnihilation** [BlockchainTokenSniper/BSCTokenSniper#80]
Hey,

I'm super uneducated in code. I know the absolute basics. But I wanted to get into using this BSCTokenSniper.

Long story short:
It doesn't matter if I pick 1 or 2 when using the launcher. It doesn't throw any errors, it just seems to accept the input. Then it proceeds to close. Nothing else happens. 

I spent a ton of time working through all the errors I was getting with the installer on my own. Idk what to do from here. Can anyone help?

Thanks.

**Comment by BlockchainTokenSniper** [comment]
Make sure you have 'pause' on the end of the .bat file and rerun. It should tell you whats wrong. If you're still unsure feel free to DM me on Telegram @BytePhoenix

**Comment by MildAnnihilation** [comment]
Thanks for the response. I tried that, still not working. I'm reaching out via Telegram as you said.
