### ISSUE TITLE
FATAL ERROR: Cannot connect to BSC node.

### ISSUE THREAD

**Issue by ChimezieMadukwe** [BlockchainTokenSniper/BSCTokenSniper#81]
I have tried v1.0 and it works flawlessly. 

But when I try to run V1.3 I get the error.

FATAL ERROR: Cannot connect to BSC node. This could be because your internet connection is unavailable, the BSC node has connectivity issues or a firewall is blocking the program's access.
Please fix the error and restart the program.

**Comment by BlockchainTokenSniper** [comment]
You should use v1.4, v1.3 and earlier are outdated and may not work. v1.4 is in the telegram link.
