### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by Clooloo** [BlockchainTokenSniper/BSCTokenSniper#83]
Hi all, 
I keep getting this error :(  What could I do? The file is right there, but I notice the double slash, is that the issue? Thanks in advance.

BSCTokenSniper v1.3

Traceback (most recent call last):
  File "BSCTokenSniper.py", line 63, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/BSCTokenSniper/torun\\config.json'
^CException ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by BlockchainTokenSniper** [comment]
If you haven’t already, use v1.4
