### ISSUE TITLE
Decompilation Activity request

### ISSUE THREAD

**Issue by rocky** [BlockchainTokenSniper/BSCTokenSniper#87]
![BSCTokenSniper-decompile-requested](https://user-images.githubusercontent.com/8851/142778128-a5b3be05-41e2-4373-94bd-f8a80776efeb.png)

![BSCTokenSniper2](https://user-images.githubusercontent.com/8851/142778239-6218ba6a-f65d-41af-bfe9-179d2010d97b.png)

**Comment by BlockchainTokenSniper** [comment]
This software is not intended to be decompiled and is strictly forbidden - "© Copyright 2021 - any attempt to sell, modify, decompile, copy or replicate this code is strictly forbidden and will result in legal action being taken."
