### ISSUE TITLE
Futures error in initNonce after getting buying signal [BSCMultiSniper v1.4.63 Beta]

### ISSUE THREAD

**Issue by vipulshah2010** [BlockchainTokenSniper/BSCTokenSniper#88]
It looks like after getting buying signal bot is giving an error. 

![image](https://user-images.githubusercontent.com/1704940/144715040-c4113722-e7b9-4786-8378-46e01a027734.png)

**Comment by minhtuyenBSC** [comment]
can you send the source code so i can fix it for you

**Comment by BlockchainTokenSniper** [comment]
join the testing group for updates to that. It's still got some issues but being updated regularly.
