### ISSUE TITLE
Bad magic number

### ISSUE THREAD

**Issue by DiegoRamirez90** [BlockchainTokenSniper/BSCTokenSniper#92]
Hello, I am trying to launch version 1.3 but I receive the error Bad Magic Number, how to solve this problem because I saw that you also had version 1.4 in test but paying $149.47 (0.4 BNB) to test it without having been able to test the later version beforehand, I am not for it because I was able to test versions 1.1 and 1.2 it works well but I would also like to test 1.3 before deciding whether or not I will donate to you too therefore to access version 1.4, thank you for your help

**Comment by BlockchainTokenSniper** [comment]
1.4 has been released, that issue should be fixed now
